"""gen-hans-chars.py — regenerate tools/hans-chars.mjs, the characters that must never reach the screen.

The game ships Traditional Chinese (Taiwan) and English only. A character is "Simplified-only" (or a non-Taiwan
variant) when OpenCC maps it to other characters and never to itself:
  STCharacters.txt  Simplified -> Traditional candidates (后 -> 後 后 keeps 后; 们 -> 們 drops 们), each candidate then
                    taken to its Taiwan form (羣 -> 群, so 群 stays allowed)
  TWVariants.txt    Traditional -> Taiwan standard form (裏 -> 裡, 着 -> 著, 爲 -> 為)
check-content.mjs (T1) and check-hant.mjs fail on any of them in a player-facing string.

Usage (from game/): pip install opencc-python-reimplemented && python3 tools/gen-hans-chars.py > tools/hans-chars.mjs
"""
import os
import opencc

DICT = os.path.join(os.path.dirname(opencc.__file__), 'dictionary')


def table(name):
    out = {}
    for line in open(os.path.join(DICT, name), encoding='utf-8'):
        parts = line.rstrip('\n').split('\t')
        if len(parts) == 2 and len(parts[0]) == 1:
            out[parts[0]] = parts[1].split(' ')
    return out


ST, TWV = table('STCharacters.txt'), table('TWVariants.txt')
out = set()
for key, values in ST.items():  # s2tw: Simplified -> Traditional candidates, then the Taiwan form of each
    if key not in [TWV.get(v, [v])[0] for v in values] and key not in values:
        out.add(key)
for key, values in TWV.items():  # a Traditional variant Taiwan does not use (裏, 着, 爲)
    if key not in values:
        out.add(key)
chars = ''.join(sorted(out))
print('// hans-chars.mjs — GENERATED by tools/gen-hans-chars.py from OpenCC (Apache-2.0); do not edit by hand.')
print('// Simplified-only characters and non-Taiwan variants: none may appear in player-facing text (check T1).')
print(f'export const HANS_ONLY = new Set([...{chars!r}]);')
# Valid Traditional characters that, in this game's text, only ever appear as the wrong conversion of a Simplified
# word (后 -> 後, 干 -> 乾 / 幹, 里 -> 裡). Allow a word in check-content.mjs (T1_ALLOW) if one is ever meant.
print("export const SUSPECT = new Set([...'后干里']);")
