// content.en.js — "250 Cups!" English content (US English).
//
// Source of truth: docs/voice/voice-script-en.md (final v2.0, C001–C100 =
// customers 1–100) and docs/voice/voice-bible.md (section 4 system lines,
// section 5 the 250 plan, section 6 style guide). Every line was rewritten for
// English comedy timing, not translated. Performance marks from the scripts
// (pauses, cut points, bold, intensity, bleep brackets) are removed here; only
// the displayable, speakable line remains. Text in (parentheses) is a stage
// direction: it is shown in small type and never read aloud. Full-width （）
// works too. The id, cat, cups, style and key fields match content.zh.js (both
// follow the v3 table in docs/lines-zh.md), so engine rules (style rotation,
// the 250 bonus, correct keys) behave the same in both languages.
//
// ---------------------------------------------------------------------------
// THE 250 PLAN (v2.0): QUARTER-WIT + "OUT OF A THOUSAND" + "A TWO-FIFTY"
// ---------------------------------------------------------------------------
// In Chinese, 二百五 ("250") means "idiot", so the clerk can insult people with
// a straight face just by saying a number. In English 250 is just a number, so
// the joke runs on three layers. The clerk never explains it and never smiles.
//   1. Quarter-wit slip (the main gag, rare): 250 is a quarter of a thousand,
//      and a quarter-wit has half the brain of a half-wit. The clerk says
//      "quarter-wit" in full, coughs, and corrects it deadpan to "a quarter...
//      of a thousand." Only in the signature routine (= #47) and the slow-motion
//      BOOKED take; never in system lines.
//   2. "Out of a thousand" (everyday layer, nothing to learn): 250/1000 is a
//      25, an F. Ties into the grading run "Failed." (#45) and "First passing
//      grade today." (#46). Example: #98 "Two-fifty." Out of a thousand.
//   3. "A two-fifty" as a rating noun, like "a ten" or "a zero": #33 alt,
//      #84, #91 ("Two-fifty-cup club only. ...Eh. Close enough.").
// Helpers: the zero family (#44 "You're missing a zero.", #65 "Two. Five.
// ...Zero."), crossing out one of 251 cups (#49), the quarters dump (#64), and
// one "eighth-wit" (#57, 125 = an eighth of a thousand). The -wit words are
// never paired with slow, special, brain cell or IQ. The old "CODE 250" shop
// code is retired. The store page carries the only explanation (not voiced):
// "In Chinese slang, '250' means idiot. Our clerk will not be explaining further."
//
// Cursing: Chinese "X你妈！" becomes "[KEYWORD] your MOM!", where the keyword is
// the word the customer stressed (seven main lines plus two alts; "ADJUST your
// MOM!" only in the signature routine). Other forms: echo ("Wait? WAIT?!"),
// "Split my ASS!", "Don't you ASK me!". Nothing stronger than damn, hell or ass,
// no remarks about anyone's mom herself, and no insults aimed at identity.
//
// style: real | curse | disdain | cold | deadpan | chuuni | math | '250' | twist
// key:   gun = "Scram!" | shut = "Zip it!" | take = "Booked!"

const C = (id, cat, name, tag, cups, says, reply, alt, style, key) =>
  ({ id, cat, name, tag, cups, says, reply, alt, style, key });

const T1 = 'Indecisive';
const T2 = 'Sugar & Ice';
const T3 = 'Toppings & Mods';
const T4 = 'Cheapskates';
const T5 = 'Quantity';
const T6 = 'Wait & Pickup';
const T7 = 'Payment';
const T8 = 'Influencers';
const T9 = 'Office Life';
const T10 = 'Weird Asks';

export const CUSTOMERS_EN = [
  // I. Indecisive
  C(1, T1, 'The Hesitator', '🤔', null, 'Ummm…',
    '(stares for three seconds, deep breath) Still thinking?|SCRAM!',
    "(checks watch) Your one second's up.|Out.", 'real', 'gun'),
  C(2, T1, 'Menu Scholar', '📖', null, "There's so much on the menu, gimme a sec…",
    "It's one page. You reading a treasure map? Scram.",
    '(snatches the menu, flips it over) …Done reading. Next.', 'disdain', 'gun'),
  C(3, T1, 'Recommend-Me', '❓', null, 'What do you recommend?',
    "Today's special: you, leaving. Runner-up: you, leaving faster.",
    '(chin-points behind them) I recommend the person behind you.', 'deadpan', 'gun'),
  C(4, T1, 'Best-Cup Seeker', '🏆', 520, "Five-twenty cups! Which one's the best?",
    '(slams counter, rises) EVERY cup! I shook them ALL! With THESE. HANDS!',
    'All of them. Next question.', 'chuuni', 'take'),
  C(5, T1, "Can't Decide", '⚖️', 100, 'A hundred cups! Milk tea or Jade Lemon…',
    "(taps the register twice) Both. A hundred each.|Two months. You're welcome.",
    "Thinking's ten bucks a second.|You're at fifty.", 'cold', 'take'),
  C(6, T1, 'Phone-a-Friend', '📞', null, 'Hold on, lemme ask my friend what they want…',
    '(snatches the phone) Hello? … Uh-huh. Your friend passes. (hangs up)|Scram.',
    'Your friend can get in line.|You? Out.', 'real', 'gun'),
  C(7, T1, 'Zoned Out', '😳', null, 'Huh? Is it my turn?',
    "Nope. Your turn's over.|Next.",
    'Huh? Thirty minutes in line…|for the vibes?', 'cold', 'gun'),
  C(8, T1, 'After-You', '🙇', null, 'Oh, you go ahead, they can order first…',
    'Generous.|Be generous… from the back.',
    "Sure. Next one's up. You go back.|Keep going. Keep going.", 'deadpan', 'gun'),
  C(9, T1, 'The Switcher', '🔄', null, 'Green tea… no, CHANGE it, black tea… CHANGE again, milk tea…',
    'CHANGE your MOM! Change again and you can change shops!',
    'Each change adds a month. Two changes? See you in four.', 'curse', 'gun'),
  C(10, T1, 'Comparison Shopper', '🍋', null, "What's the difference between Jade Lemon and Lemon Green?",
    "(points at the menu) One's on the left. One's on the right. Order.",
    "Difference? You haven't ordered.", 'deadpan', 'shut'),

  // II. Sugar & Ice
  C(11, T2, 'Sugar Picker', '🍬', null, 'Can I pick my sugar level?',
    'Sure. Your options: golden ratio.|…Great choice.',
    "(rips up the sugar chart) …Chart's gone.|No more picking.", 'cold', 'shut'),
  C(12, T2, 'Less-Ice Crew', '🧊', null, 'Can I get LESS ice?',
    'Less ice? The ice showed up to work.|You want me to do layoffs?',
    'LESS your MOM! Full ice tastes better!', 'deadpan', 'shut'),
  C(13, T2, 'No-Ice Crew', '❄️', null, 'No ice.',
    '(hand over face) Ice… is the SOUL. You want me to… ERASE it?!|NEVER!',
    'Hold the ice?|Hold your spot. In the back.', 'chuuni', 'shut'),
  C(14, T2, 'Light-Ice Crew', '🌡️', null, 'Just light ice.',
    "Light ice? (turns, yells to the back)|FULL ICE! Customer's OVERHEATING!",
    '(nods) Light ice. Heard.|Regular ice.', 'real', 'shut'),
  C(15, T2, 'Half-Sugar Crew', '🍯', 100, 'A hundred cups, half sugar.',
    "Life's bitter enough.|Full sugar. You're welcome.",
    '(eyes soften) …Rough week, huh? (instantly mean)|FULL SUGAR! NEXT!', 'deadpan', 'take'),
  C(16, T2, 'No-Sugar Crew', '🚫', null, 'No sugar, thanks.',
    "No sugar? That's twenty extra. (customer blinks)|…Sugar-removal fee.",
    "(clutches chest, staggers back) You've wounded…|the GOLDEN RATIO… FULL SUGAR!", 'math', 'shut'),
  C(17, T2, 'Hot-Drink Crew', '🔥', null, 'Can you SWITCH it to hot?',
    "SWITCH your MOM! It's ninety-five out. Give it a minute.",
    "Sure. (points outside) Stand out there. Two months, it's hot.", 'curse', 'shut'),
  C(18, T2, 'Sore Throat', '🤒', null, 'Not too cold, my throat hurts.',
    "Sore throat? Doctor's orders:|zip it.",
    "(cups an ear) …Huh? Can't hear you.|Regular ice.", 'disdain', 'shut'),
  C(19, T2, 'On-the-Side', '🥄', null, 'Can I get the sugar and ice on the side?',
    "Sure. Sugar's yours. Ice is yours. The tea's mine.",
    "(shakes head) No. The golden ratio is family. We don't split up family.", 'cold', 'shut'),
  C(20, T2, 'Percent Nerd', '💯', 251, 'Two-fifty-one cups, thirty-seven percent sugar?',
    'What? Thirty-seven? (mashes the calculator forever) …No button for that. Golden ratio. Booked.',
    'Sure. Thirty-seven percent… of full sugar.', 'real', 'take'),

  // III. Toppings & Mods
  C(21, T3, 'Add-Boba', '🧋', null, 'Can I ADD boba?',
    "Sure. Add it, and it's a different drink. That drink's sold out.",
    'ADD your MOM! The original is PERFECT!', 'deadpan', 'shut'),
  C(22, T3, 'More Boba', '⚫', null, 'Can I get more boba?',
    '(shields the boba pot) Every pearl… has a SERIAL NUMBER! NO ONE takes extra!',
    'Counted. Every pearl. Want more? Count them yourself.', 'chuuni', 'shut'),
  C(23, T3, 'The Swapper', '🔀', null, 'Can I swap coconut jelly for grass jelly?',
    'Sure. Swapping to— no.',
    'Swap? Swap places. Back of the line.', 'cold', 'shut'),
  C(24, T3, 'Everything-On-It', '🌈', 100, 'A hundred cups! ALL the toppings!',
    '(eyes light up) You get it! You actually GET it! (instantly cold) …Two months.',
    "Four toppings. Ten bucks each. A hundred cups. …That's four grand.", 'twist', 'take'),
  C(25, T3, 'Boba Remover', '🥢', null, 'Can you take the boba out?',
    "(looks at the boba, then at the customer) …What'd they do to you?",
    'Sure. Pick them out yourself. One by one. Outside.', 'real', 'shut'),
  C(26, T3, 'Oat-Milk Ask', '🌾', null, 'Do you have oat milk?',
    'Oat milk? Cute. Whole milk. Next.',
    'No. We have a line. Want that?', 'disdain', 'shut'),
  C(27, T3, 'Pudding Halver', '🍮', null, 'Can I get HALF a pudding?',
    'HALF your MOM! Pudding comes WHOLE!',
    'Sure. Half now. Other half in two months.', 'curse', 'shut'),
  C(28, T3, 'Strong-Tea Fan', '🍵', null, 'Can you make the tea stronger?',
    'Any stronger, it needs a prescription.',
    '(sighs, audible) …The coffee place is next door.', 'disdain', 'shut'),
  C(29, T3, 'Extra Lemon', '🍋', 100, 'A hundred cups, extra lemon slices.',
    '(bites a whole lemon, straight-faced) …Sour enough. Booked.',
    '(gazes into the distance) Each lemon slice… has its own DESTINY!', 'real', 'take'),
  C(30, T3, 'Mad Scientist', '🧪', null, 'Black tea plus green tea plus milk plus lemon.',
    "All four? (slides it back) That's dishwater. Next.",
    '(taps calculator) Four add-ons… comes to two-fifty. Out of a thousand. Checks out.', 'disdain', 'shut'),

  // IV. Cheapskates
  C(31, T4, 'Discount Hunter', '🏷️', 250, 'Two-fifty cups—can I get a discount?',
    '(grips ticket) Our prices… are UNDEFEATED! BOOKED!',
    '(slides a calculator over) Discount applied: zero percent. Booked.', 'chuuni', 'take'),
  C(32, T4, 'BYO Cup', '♻️', 100, 'A hundred cups—do I get the reusable cup discount?',
    'BYO cup: five off. Cup-washing fee: fifty. Do the math.',
    'Sure. Leave the cups. Pick them up in two months.', 'math', 'take'),
  C(33, T4, 'Bucket Guy', '🪣', null, 'I brought my own cup! (holds up a bucket)',
    '(stares at the bucket, then at the customer) …Is there a fire? Beat it.',
    '(eyes the bucket) …Fits two-fifty. (eyes the customer) Classic two-fifty.', 'real', 'gun'),
  C(34, T4, 'Sample Seeker', '🥤', null, 'Can I get a PREVIEW? Just a little?',
    "PREVIEW your MOM! The premiere's in two months!",
    'A sample? This drink exists in two months. Want to sample the air?', 'curse', 'gun'),
  C(35, T4, 'Nine Stamps', '⭐', null, "I've got nine stamps—just give me the tenth?",
    "(stamp hovers… pulls back) Nine's a great number. Keep it.",
    'Nine? (rips up the card) Start over.', 'twist', 'gun'),
  C(36, T4, 'Haggler', '🤝', 520, 'Five-twenty cups, cut me a deal~?',
    "A deal? Sure. (taps calculator) …Congrats. It's more.",
    "Haggle? This isn't a flea market. Booked.", 'math', 'take'),
  C(37, T4, 'Extra Bag', '🛍️', null, 'Can I get an extra bag?',
    '(pulls out a bag, looks at it, puts it back) …Nah. Thought about it. No.',
    "Bag's ten cents. What're you even putting in it?", 'real', 'shut'),
  C(38, T4, 'Separate Bags', '📦', 50, 'Fifty cups—can I get them bagged separately?',
    'Ten bucks a bag. Fifty cups. Do the math! SCRAM!',
    'Sure. Separate bags. Separate waits. Two months each.', 'math', 'gun'),
  C(39, T4, 'BOGO Hunter', '✌️', 251, 'Two-fifty-one cups—any buy-one-get-one half off?',
    "Yep. First cup's double. Booked.",
    "Yep. Every two-fiftieth cup's half off. …Your number's very popular here.", 'cold', 'take'),
  C(40, T4, 'Freeloader', '🆓', null, 'Can the toppings be free?',
    '(slowly rises) Free? The only thing free in this world… is my EYE ROLL!',
    '(turns to empty air) …They said free. (turns back) Ha. Ha. Shoo.', 'chuuni', 'gun'),

  // V. Quantity
  C(41, T5, 'One Cup', '1️⃣', 1, 'One cup.',
    'One cup? You stood in line for ONE?|Scram.',
    'One cup? Two months. Two-fifty? Also two months.|Your call.', 'disdain', 'gun'),
  C(42, T5, 'Three Cups', '3️⃣', 3, 'Three cups.',
    "Three cups… (turns, looks at the line) …They're writing a one-star review.|About you.",
    'Three cups. Two months. Twenty days a cup.|Worth it?', 'real', 'gun'),
  C(43, T5, 'Fifteen Cups', '🔢', 15, 'Fifteen cups.',
    "(doesn't even look) Too small.|SCRAM!",
    "(doesn't look) Fifteen.|Next.", 'disdain', 'gun'),
  C(44, T5, 'Twenty-Five', '🔢', 25, 'Twenty-five cups.',
    "Twenty-five? You're missing a zero.|Go find it.",
    '(lip twitches) …Twenty-five.|One zero away from your real number.', '250', 'gun'),
  C(45, T5, 'Fifty Cups', '🔢', 50, 'Fifty cups.',
    "(doesn't look) Fifty. Failed.|Next.",
    'Fifty… (sighs, audible) So close.|Bye.', 'cold', 'gun'),
  C(46, T5, 'One Hundred', '💯', 100, 'A hundred cups.',
    'A hundred… (ticks a box in a tiny notebook) First passing grade today.|Booked.',
    "(almost smiles) …Ahem. It's fine.|Booked.", 'deadpan', 'take'),
  C(47, T5, 'Two-Fifty', '💰', 250, 'Two-fifty!',
    '(suddenly calm, professional) Okay. Two-fifty. A quarter-wit— (cough) a quarter… of a thousand.|Of what?',
    '(eyes well up) Finally… (instantly cold)|Two-fifty of WHAT? Spit it out!', '250', 'take'),
  C(48, T5, 'Two-Forty-Nine', '🔢', 249, 'Two-forty-nine cups.',
    '(shoots up) ONE. CUP. SHORT!! Come back COMPLETE!',
    'Two-forty-nine? …One short. You did that on purpose.', 'chuuni', 'gun'),
  C(49, T5, 'Two-Fifty-One', '🔢', 251, 'Two-fifty-one!',
    'Two-fifty-one? (crosses one out)|Two-fifty. Booked.',
    'Thought one extra cup would save you?|…Two-fifty. Booked.', 'cold', 'take'),
  C(50, T5, 'Five-Twenty', '💘', 520, "Five-twenty cups! It's for my crush!",
    '(blushes, one sec) Your crush can wait.|Two months.',
    'Confessions? Different shop.|Booked.', 'twist', 'take'),

  // VI. Wait & Pickup
  C(51, T6, 'The Wait Asker', '⏳', null, "How long's the WAIT?",
    'Wait? WAIT?! Two months! Ask again— three!',
    "Two months. (stares, doesn't blink) …You just waited three more seconds.", 'curse', 'shut'),
  C(52, T6, 'The Pinger', '⏰', null, 'Is mine ready yet?',
    "Ask again? (rips a calendar page) That's a month.",
    '(slowly turns to the calendar… turns back) …No.', 'math', 'shut'),
  C(53, T6, 'The Why Guy', '🤨', null, 'Why does it take two MONTHS?',
    'The lemons are still blooming.',
    "Because you asked. Now it's three.", 'deadpan', 'shut'),
  C(54, T6, 'The Rusher', '🏃', null, "I'm in a hurry!",
    "In a hurry? And you got in LINE? Leaving's faster. Bye.",
    '(slowly clenches fist) The whole world can rush… the GOLDEN RATIO never speeds up!', 'disdain', 'gun'),
  C(55, T6, 'The Ticket Loser', '😱', null, 'I lost my ticket…',
    '(slowly tears off a new one) New ticket. Clock resets. Next.',
    "No problem. We go by ticket, not by face. That cup's your donation.", 'deadpan', 'gun'),
  C(56, T6, 'The Returner', '🧔', 250, 'I ordered two-fifty cups two months ago…',
    '(flips the ledger) Two-fifty… found it. (slams it shut) We start tomorrow.',
    "(eyes go misty) You actually came back… (instantly hard) Hold your number. We'll call you.", 'cold', 'take'),
  C(57, T6, 'The Half-Pickup', '🌗', null, "It's been a month. Can I grab half now?",
    "Half? One twenty-five? That's an eighth-wit. …Don't sell yourself short.",
    'Sure. The half you take early? Plus a month.', '250', 'gun'),
  C(58, T6, 'The To-Go Order', '🥡', 520, 'Five-twenty cups, to go.',
    '(thrusts the ticket skyward) Five-twenty… TO GO… Two months from now— we MEET AGAIN!',
    "(doesn't look up) Obviously. You planning to live here two months?", 'chuuni', 'take'),
  C(59, T6, 'The Reserver', '📅', null, 'Can I book tomorrow at three?',
    '(flips to the very last page) … Next opening: never. Want me to pencil you in?',
    '(turns to the line) They want a reservation. (whole line laughs) …Shoo.', 'cold', 'gun'),
  C(60, T6, 'The Counter Caller', '☎️', null, "(phone to ear, standing right there) Hi, yeah, I'd like to order…",
    '(counter phone rings, picks up, looks straight down) … I can see you. (hangs up) Scram.',
    "(answers) Thanks for calling. You're caller number two-fifty. Your call is important to us. Hold for two months.", 'real', 'gun'),

  // VII. Payment
  C(61, T7, 'The Card Tapper', '💳', 100, 'A hundred cups. Can I tap to pay?',
    'Sure. (hoists the card reader to the very top of the counter) …Tap it if you can reach it.',
    "Card's an extra month. Tap away.", 'deadpan', 'take'),
  C(62, T7, 'The QR Fumbler', '📲', null, "Hold on, lemme SCAN this… it's not scanning…",
    'SCAN your MOM! (grabs a broom) Clean-up on aisle YOU!',
    "(glances at their phone) …Your Wi-Fi's on a two-month wait too.", 'curse', 'gun'),
  C(63, T7, 'The Big Bill', '💵', 251, 'Two-fifty-one cups. Can you break a hundred?',
    "Can't break it. (hands over ticket) Here's your change.",
    'A hundred, minus the change-making fee… exactly a hundred.', 'cold', 'take'),
  C(64, T7, 'The Coin Dumper', '🪙', 100, '(dumps a mountain of quarters) A hundred cups!',
    "You count 'em. By the time you're done— pickup.",
    "(stares at the coin mountain, rises slowly) This isn't money… it's your OBSESSION! BOOKED—!", 'math', 'take'),
  C(65, T7, 'The Rewards Member', '🧾', null, 'Can you add it to my rewards?',
    "Phone number? (types, reading aloud) Two. Five. …Zero. That's you now.",
    '(slaps the ticket onto their forehead) Saved.', '250', 'shut'),
  C(66, T7, 'The Expenser', '🏢', null, 'I need an itemized receipt. For work.',
    "Company's paying? (eyes light up) (coughs, stone-faced) …Two-fifty minimum.",
    'Expensing adds a month. Company money is still money.', 'twist', 'shut'),
  C(67, T7, 'The Splitters', '👥', null, 'Can we SPLIT the check?',
    'Split my ASS! Whoever pays stays. Everyone else, out!',
    'Sure. Split pay, split lines, split two months. Each.', 'curse', 'gun'),
  C(68, T7, 'The Pay-Later', '🧋', 520, "Five-twenty cups. Can I pay you after I drink 'em?",
    "(slams the counter, rises) Drink first?! PAY first— then you're WORTHY!",
    'Sure. You drink in two months. You pay now.', 'chuuni', 'take'),
  C(69, T7, 'The Price Asker', '💲', null, 'How much is this one?',
    'Asking the price is ten bucks. (customer opens mouth) …Twenty.',
    '(points at the menu board, points at them, points at the board, silence)', 'math', 'shut'),
  C(70, T7, 'The Receipt Demander', '📜', 250, 'Two-fifty cups. Receipt.',
    '(tears a corner off the ticket, flicks it down) Receipt. Happy?',
    '(holds the ticket aloft) Receipt, rewards, pickup pass— ALL IN ONE!', 'disdain', 'take'),

  // VIII. Influencers
  C(71, T8, 'The Photographer', '📸', null, 'Can I take a pic?',
    'Ten bucks a pic. Me in it, twenty. Flash on— scram.',
    'Sure. (turns around, back to the camera) Go ahead.', 'math', 'gun'),
  C(72, T8, 'The Shop Reviewer', '📱', null, "Hiii chat! Today we're reviewing the MEANEST boba shop in town!",
    "(leans into their camera) Chat, they're gone in three. Three, two— SCRAM.",
    'Review noted. …One star. For you.', 'real', 'gun'),
  C(73, T8, 'The Streamer', '🎥', null, "I'm live! Say hi to chat?",
    '(to camera) Hi. Get in line. (hands phone back)',
    '(grabs the phone) Chat… behold… the LONGEST line in town!', 'cold', 'shut'),
  C(74, T8, 'The Story Poster', '📍', null, 'If I post a story, do I get free boba?',
    "A story? Here's your story: SCRAM.",
    'One per like. (checks their phone) …Three likes. Three boba. Two months.', 'disdain', 'gun'),
  C(75, T8, 'The Selfie Seeker', '🤳', 250, 'Two-fifty cups! Can I get a selfie with you?',
    '(sneaks a quick hair fix) (instantly stone-faced) …Fast. Two-fifty a pic.',
    '(dead-faced peace sign) Two-fifty a pic. …Seems fair.', 'twist', 'take'),
  C(76, T8, 'The One-Star Threat', '⭐', null, "I'm writing you a one-star review!",
    'Noted. Your review will be ready in two months.',
    '(whips out phone, jabs the screen) Already gave you negative one.', 'deadpan', 'gun'),
  C(77, T8, 'The Comp Seeker', '🎁', null, "I'm an influencer. Can I get it comped?",
    '(gazes skyward) Comped?! I bow to no follower count… only to the GOLDEN RATIO!',
    'Comped? One word: scram.', 'chuuni', 'gun'),
  C(78, T8, 'The Pic-and-Dash', '🚶', null, '(snaps photo, turns to leave)',
    '(grabs a megaphone) Pic-and-dash! (whole line turns) …Yeah. You. Scram.',
    'One pic, one cup. You took fifteen. Pay up.', 'real', 'gun'),
  C(79, T8, 'The Critic', '🍷', null, 'Let me APPRECIATE the finish first…',
    "APPRECIATE your MOM! You don't even HAVE it yet!",
    'The finish? Two months. Appreciate it then.', 'curse', 'shut'),
  C(80, T8, 'The Cup Writer', '✍️', 100, 'A hundred cups. Write "Happy Birthday" on every one!',
    '(scribbles one) "Pick up… in two months." …Happy birthday. Booked.',
    "(writes gorgeous calligraphy, realizes it's too nice, crosses it out) …Hold your number.", 'cold', 'take'),

  // IX. Office Life
  C(81, T9, 'The Client', '🧑‍💼', 250, 'Two-fifty cups. Premium, but not pricey.',
    '(hands ticket) Premium: two months. Cheap: next door.',
    '(scans the order up and down) …Premium is the wait. Booked.', 'disdain', 'take'),
  C(82, T9, 'The Contradiction', '🎨', 100, 'A hundred cups. Sweet but not too sweet, cold but not too cold.',
    '(to the back) Hundred, normal! (back of house: "HEARD!")',
    'Two contradictions. Ten bucks each. Booked.', 'real', 'take'),
  C(83, T9, 'The Rush Boss', '📌', 100, 'A hundred cups. All RUSH!',
    'Rush? Two months. SUPER rush— (stamp) three.',
    "All rush? Then nothing's rush. Booked.", 'deadpan', 'take'),
  C(84, T9, 'The Office Order', '📋', 100, "I'm ordering for the whole office, like a hundred, lemme double-check…",
    "Don't bother. Whole office: two-fifty. Fits the team.",
    '(eyes their floor-length list) …Hold a meeting. Then order.', '250', 'take'),
  C(85, T9, 'The Manager Caller', '👔', null, 'Get me your manager!',
    '(climbs onto the stool) Manager?! On THIS counter— nobody stands HIGHER! SCRAM!',
    "Manager? In the back. (points to the end of the line) Get there, you'll meet them.", 'chuuni', 'gun'),
  C(86, T9, 'The "I\'m the Customer"', '👑', null, "Excuse me, I'm the customer!",
    "You haven't ordered. You're not a customer. You're a bystander.",
    '(slow nod) Mm. (keeps nodding) Mm-hm. …Ordering or not?', 'cold', 'gun'),
  C(87, T9, 'The Nitpicker', '🙄', null, "There's no actual jade in the Jade Lemon.",
    'Correct. Buffalo wings have no buffalo. Ordering?',
    'Jewelry store? Down the street. Next.', 'deadpan', 'shut'),
  C(88, T9, 'The Complainer', '📝', null, 'I want to file a complaint!',
    "Sure. (hands ticket) Complaints wait in line too. You're number two-fifty.",
    'Complaint form. Results in two months.', '250', 'gun'),
  C(89, T9, 'The Name-Dropper', '🤝', null, 'I know the owner, you know.',
    'So do I. They said zip it.',
    '(snaps to attention) Friend of the owner! (squints) …Nope. Order.', 'cold', 'shut'),
  C(90, T9, 'The "Just a Question"', '🙋', null, 'I just wanna ASK real quick—',
    "ASK?! Don't you ASK me! Asking waits in line too!",
    '(finger traces the line out the door, down the block, out of sight) …Ask down there.', 'curse', 'gun'),

  // X. Weird Asks
  C(91, T10, 'The Restroom Ask', '🚻', null, 'Can I use your restroom?',
    'Restroom? Two-fifty-cup club only. …Eh. Close enough.',
    'Sure. Return it in two months.', '250', 'gun'),
  C(92, T10, 'The Charger Ask', '🔋', null, 'Can I charge my phone here?',
    '(melts onto counter) Same. One percent. You gonna charge me?',
    "Sure. Outlet's outside. Third lamppost.", 'real', 'gun'),
  C(93, T10, 'The Wi-Fi Ask', '📶', null, 'Got Wi-Fi?',
    'Yep. Network: NEXT. Password: SCRAM.',
    "Yep. Password: two-five-oh, two-five-oh. …You'll remember it.", 'deadpan', 'gun'),
  C(94, T10, 'The Sitter', '🪑', null, 'Can I get a CHAIR?',
    "CHAIR your MOM! Two months standing— that's the FLAVOR!",
    'Sure. Sit outside. Two months.', 'curse', 'shut'),
  C(95, T10, 'The Heat Complainer', '🥵', null, 'Can you crank the AC?',
    '(eyes closed, arms wide) A calm mind… is a COOL mind! The REAL ice… is in the CUP!',
    "Ten bucks a degree. It's seventy-eight in here. Sixty-eight? That's a hundred.", 'chuuni', 'shut'),
  C(96, T10, 'The Shaker', '🌀', 251, "Two-fifty-one cups. Can you shake 'em?",
    '(picks up a cup, whole body shakes with it) …Happy? Booked.',
    '(raises the shaker high) No shaking! The golden ratio— is BORN BALANCED!', 'real', 'take'),
  C(97, T10, 'The Dog Owner', '🐕', null, 'Can my dog have some?',
    '(looks at the dog, looks at them) Dog can stay. You can go.',
    "Sure. Dogs wait two months too. It's more patient than you.", 'cold', 'gun'),
  C(98, T10, 'The Name Writer', '🏷️', 100, 'A hundred cups! Put my name on every one!',
    '(writes) …Done. "Two-fifty." Out of a thousand. Booked.',
    "Name? You're a number.", '250', 'take'),
  C(99, T10, 'The Smile Request', '😁', 100, "Smile and I'll order a hundred!",
    '(stiff smile, three full seconds) …Done. Three hundred bucks. Booked.',
    "(lip twitches three times, gives up) …Can't. Next.", 'math', 'take'),
  C(100, T10, 'The Kind One', '🫶', null, "Um… how's your day going?",
    '(freezes 0.3 s, lip wobbles) …Was great. Then you asked. SCRAM!',
    '(gazes upward) My mood…? Like the ice— FULL. And COLD! SCRAM!', 'twist', 'gun'),
];

// System voice: voice-bible.md section 4 (SNX, SSV, SBO, SBR, SQM, SCL) and
// the signature routine in section 5.5 (SIG01–SIG08).
export const SYSTEM_EN = {
  next: [
    'NEXT!',
    'Neeeext—!',
    "(doesn't look up) Next.",
    'Next. Move.',
    '(sighs) …Next.',
    "You're done? Great. NEXT!",
    'NEXT! …I said NEXT!',
    'You. Up.',
    'Next two-fif— (coughs) NEXT!',
    'NEXT! Numbers out!',
  ],
  polite: [
    'Hiii~! What can I get started for you today~?',
    'Welcome in~! What are we feeling today?',
    "Can I recommend something? I'd love to~",
    'No rush! Take all the time you need~',
    "Any sugar, any ice~ You're the boss!",
    'Extra boba? On the house~!',
    "I'm so sorry for the wait. Truly. From the bottom of my heart~",
    'Coming right up~! Just three minutes, promise!',
    "Long day? This one's on me, okay~?",
    'Your smile literally makes my whole shift~!',
    'Thank you so much~! Get home safe, come back soon~!',
    'Is there anything else I can do to make your day better~?',
  ],
  boo: [
    'BOOOOO!',
    'Customer service?! HERE?!',
    "Where's the attitude?!",
    'Refund the yelling!',
    'That was NICE! Gross!',
    'Yell at us! Boooo!',
  ],
  rageStart: [
    '(stomps onto counter) EVERYBODY— LINE UP!!',
    'Tonight— we yell till CLOSING!!',
    'This counter… is MY ARENA!!',
    'GOLDEN RATIO— OVERDRIVE!!',
  ],
  rageLines: [
    'SCRAM!',
    'Too small!',
    'You too!',
    'Out-out-out!',
    'Back!',
    'Still thinking?',
    "Door's there!",
    'Failed!',
    'Bye!',
    'One short!',
    'ZIP IT!',
    'Shh!',
    'No adjusting!',
    'Full ice!',
    'Full sugar!',
    'No questions!',
    'No samples!',
    'No haggling!',
    'Zip-zip-zip!',
    'Ten bucks!',
    'BOOKED!',
    'Number!',
    'Two months!',
    'Hold it!',
    'Stamped!',
    'Two-fifty!',
    'Golden ratio!',
    'Stamp-stamp-stamp!',
    'Do the math!',
    'Made to order!',
    'NEXT!',
    'You!',
    'And you!',
    'Faster!',
    'Again!',
    'ALL of you!',
  ],
  milestones: {
    10: "(shutter rattles up) Line's out the door! How many cups?",
    100: "What's this line for? (doesn't look up) Me.",
    1000: 'Please line up this way. Do not run. …Line hit the subway. Cute.',
    10000: "Breaking news: a line is wrapping around downtown! We're on TV. Next.",
    100000: "Live from the news chopper: this line goes on for BLOCKS! You. Up there. Back of the line.",
  },
  closing: [
    'SOLD OUT! Everybody— come back in TWO MONTHS!',
    "CLOSED! Still in line? Your spot's good till tomorrow.",
    '(shutter halfway down) Still here? …Good. Come earlier tomorrow.',
    "That's all the two-fifties for today. Closed!",
    "(shutter slams) …Shop's shut. Hold your numbers.",
    "Today's business— is OVER! And tomorrow… you'll ALL get SCRAMMED again!",
  ],
  ui: {
    gun: 'Scram!',
    shut: 'Zip it!',
    take: 'Booked!',
    queue: 'Line',
    aura: 'Swagger',
    fury: 'Fury',
    start: 'Open Shop!',
    again: 'Yell Another Day',
    bleep: 'Bleep',
  },
  start: {
    title: '250 Cups!',
    subtitle: 'Rude clerk. The ruder, the longer the line.',
    start: 'Tap to open',
    startDay: 'Open (Day {n})',
    skip: 'Skip ▸',
  },
  // Day 1 opening routine (docs/first-minute-spec.md section 3, driven by src/opening.js). Same keys and
  // the same '|' cut points as SYSTEM_ZH.opening. The number stays "250" on screen; TTS reads it
  // "two-fifty" (audio.ttsText). r3 carries the full quarter-wit slip: the opening IS the signature
  // routine, the one place voice-bible 5.4 allows it. Customers are "they" (appearance is random).
  opening: {
    dayCard: 'DAY 1 · NIGHT MARKET',
    ask: 'How many cups?',
    c1: 'Ummm…', r1: 'Still thinking?|SCRAM!',
    c2: '15 cups!', r2: '15 cups?|Too small. SCRAM!',
    c3: '250 cups!', r3: 'Okay. 250. A quarter-wit— (cough) a quarter… of a thousand. Of what?',
    c3b: 'The signature Jade Lemon!', r3b: 'Want me to adjust the sugar or ice?',
    c3c: 'Yeah, adjust it! Less sugar, less ice!',
    r4: 'ADJUST your MOM!', r4b: 'The golden ratio is PERFECT!', r4c: "Everything's made fresh to order.",
    r4d: '250 cups,', r4e: 'pick up in two months.', r4f: "Here's your pickup number.",
    next: 'NEXT!',
    signs: { s1: 'Ummm…', s2: '15 cups', s3: '250 cups', s3b: 'Signature Jade Lemon', s3c: 'Less sugar, less ice', s3cSub: 'no ice… half sugar…' },
    cue: { r1: 'SCRAM', r2: 'SCRAM', r4: 'ADJUST' },
    wrong: {
      w1shut: "Zip it? They haven't said a word.", w1take: 'Booked? They never said how many.',
      w2shut: "They said 15 cups. That's not noise.", w2take: '(picks up the ticket, puts it back) …15 cups? Too small.',
      w3gun: 'SCRAM—', w3gunAfter: '…Wait. How many cups?',
      w3shut: 'ZIP—', w3shutAfter: '…250 cups? That gets booked.',
      w4gun: "Order's booked. Now they need to zip it.", w4take: "Already booked! Now they're making demands—",
      auto: "Fine. I'll do it myself.",
    },
    timeout: {
      t1: 'Hiii~ Take all the time you need~', t2: '15 cups~? Coming right up~',
      t3: '250 cups~ Thank you so much~', t4: "Of course~ Less sugar, less ice~ I'll adjust it for you~",
      notMe: "…That wasn't me.",
      // later timeouts rotate (review: five timeouts all said the same line)
      notMeAlt: ['…That was work-mode me.', "…That one doesn't count.", '…You heard nothing.'],
    },
    hz: {
      setup1: 'Still thinking?', punch1: 'SCRAM!',
      setup2: '15 cups?', setup2b: 'Too small', punch2: 'SCRAM!',
      huh: '???', proud: '(confident)', big250: '250',
      calm: '(suddenly very calm)', trap: '(trick question)', adjusting: '(still adjusting)', handStop: '(hand freezes)',
      punch4: 'ADJUST YOUR MOM!', gold: 'GOLDEN RATIO!', fresh: 'Made to order', cups250: '250 cups', twoMonths: 'TWO MONTHS',
      stunned: '(frozen)', next: 'NEXT!', logo: '250 CUPS!',
    },
    recap: ['Ummm… / 15 cups → Scram', '250 cups → Booked', 'Less sugar, less ice → Zip it'],
    plate: ['No.001', '250 cups', 'Pick up in 2 months'],
    closing: {
      title: 'Day 1 · Closed',
      lines: ['Ummm… / too few cups → Scram', 'Making demands → Zip it', 'Big order → Booked'],
      queueFmt: '{title} | {n} in line',
      tap: 'Tap for Day 2',
    },
  },
  // Day 3+ "original" customer (two steps: Booked → Zip it). Not one of the 100.
  originalCustomer: {
    id: 'orig', name: 'The Original', cat: 'Quantity', steps: ['take', 'shut'], key: 'take', style: '250', cups: 250,
    says: '250 cups!', says2: 'Yeah, adjust it! Less sugar, less ice!', sign2: 'Less sugar, less ice',
    reply1: 'Okay. 250 cups of what?', reply2: 'ADJUST your MOM!|The golden ratio is PERFECT!',
  },
  tips: { gun: 'Red slip = Scram', shut: 'Purple = Zip it', take: 'Gold = Booked' },
  unlock: { aura: 'No swagger = forced politeness', rage: 'RAGE!', rageTip: 'Every key works!', charge: 'FULL FORCE!' },
  daySlow: 'Too slow! Forced politeness',

  // ---- Gameplay v2 stage 2 (docs/gameplay-v2.md 5–6; lines from docs/lines-v2-draft.md 7–8)
  // Day name, one-line rule (day card), ★2 goal and ★3 blackboard riddle. Display only.
  days: {
    1: { name: 'Opening Night', rule: 'Read the sign: Scram, Zip it, Booked', star2: 'Combo 10', riddle: "He hasn't finished his Ummm." },
    2: { name: 'Lunch Rush', rule: 'Watch the next two. 5 right in a row = Fast Mouth', star2: '15 in a row in Fast Mouth', riddle: 'The one behind is in a hurry.' },
    3: { name: 'Original Day', rule: '250-cup guy: Book him, then zip it', star2: 'Both steps right on 4 originals', riddle: 'A tribute to the original.' },
    4: { name: '250 Day', rule: 'Book cups until the ticket hits exactly 250', star2: 'Hit exactly 250 twice', riddle: 'One short is one short.' },
    5: { name: 'Talk-Back Day', rule: 'The ex-boss calls: two taps to hang up', star2: 'Combo 40', riddle: "He's not done talking." },
    6: { name: '8 PM Rush', rule: 'Tap through groups. Let order-changers finish', star2: 'Clear 3 groups', riddle: 'One cup and you queued?' },
    7: { name: 'The Ex-Boss', rule: 'Answer every step. Hold the last one', star2: 'Beat the ex-boss, no timeouts', riddle: 'His last discount.' },
  },
  report: {
    day: 'Day {n}', rule: "Today's rule", riddle: 'Blackboard', rating: 'Rating', newRecord: 'NEW RECORD!', best: 'Best',
    toStar3: 'For ★3: ', allStars: 'All three stars!', star1: '★1 {n} in line', star1Boss: '★1 Beat the ex-boss',
    star2: '★2 ', star3: '★3 ', tomorrow: 'Tomorrow: ',
  },
  quick: { start: 'FAST MOUTH!', label: 'Fast Mouth' },
  eventUi: {
    megaphone: { title: 'Megaphone guy', hint: 'MASH!' },
    phone: { title: 'Ex-boss calling', hint: 'Tap twice to hang up' },
    calculator: { title: 'Calculator', hint: 'Hold Booked, let go on 250' },
    stamp: { title: 'Stamp every cup', hint: 'MASH Booked!' },
    shutter: { title: 'Pull the shutter!', hint: 'MASH!' },
    group: '×{n}',
  },
  meter: {
    label: 'Booked', unit: 'cups',
    plate: ['No.250', '250 cups', 'Pick up in 2 months'],
    over: [
      'Two months… (checks the ticket)|oh. Six months.',
      'Over. (rips the ticket)|Start over.',
      'Two-fifty-something? (drinks the extras)|Okay. Zero.',
      "Over two-fifty?|That's worse than a two-fifty.",
      '(flips to the last page) Out of pages.|See you next year.',
    ],
    hit: [
      '…Two-fifty. Exactly. (gold stamp)|Number two-fifty, hold your ticket.',
      '(WHAM, gold stamp) Two-fifty.|Not one more. Not one less.',
      'EXACTLY— TWO— FIFTY!!|(sits right back down) Pick up in two months.',
    ],
  },
  calculator: {
    sign: '250 cups\nhow much?',
    start: "(pulls out the calculator) Fine.|Let's do math.",
    jackpot: '(taps calculator) Four add-ons… comes to two-fifty.|Out of a thousand. Checks out.',
    r249: "Two-forty-nine? One short.|You're short more than one. Booked.",
    r251: 'Two-fifty-one? The extra one|is mine. Booked.',
    r300: 'Three hundred? (shakes the calculator)|You broke it. Booked.',
    r0: 'Zero? (stares at the calculator)|…Same as your effort. Booked.',
  },
  megaphone: {
    passer: ["(megaphone) This shop's clerk is SO MEAN—!", '(megaphone) Two hours in line— and I got YELLED at—!', "(megaphone) But it's SO GOOD—!"],
    shout: ['(grabs a megaphone) HEY—!', 'Line up—!', 'Two months—!', 'Golden ratio—!', 'Full sugar—!', 'Hold your number—!', 'NEXT—!'],
    end: '(lowers the megaphone, calm) …Thanks for stopping by.|Next.',
  },
  phone: {
    caller: "Hey, it's me. Your old manag—",
    hangup: ['(checks caller ID, swipes) …Wrong number.|NEXT.', '(swipes) Spam call.|NEXT.', '(answers, listens one second) …The number you have dialed is busy shaking drinks. (hangs up)|NEXT!'],
  },
  stamp: {
    cust: 'Two-fifty cups! Stamp every single one!',
    sign: 'Stamp\nevery cup',
    callouts: { 50: 'Fifty!', 100: 'A hundred!', 200: 'Two hundred!', 249: 'Two-forty-nine…' },
    done: '(panting) …Done.|Pick up in two months.',
  },
  group: {
    take: ['(one finger sweeps the row) You, you, you—|BOOKED! Two months!', '(slams the counter) You lot—|two months, together! BOOKED!'],
    gun: ['(sweeps) You, you, you, and YOU—|SCRAM! NEXT!'],
    shut: ['(one wave of the palm) One, two, three—|ALL of you, zip it!'],
  },
  changeOrder: {
    name: 'Order Changer',
    says: 'Green tea… no, black tea… wait—', says2: '…Make it two-fifty!', sign: 'Green tea…\nblack tea…', sign2: '250 cups',
    early: '(cuts in before the next change) No changes.|Scram. NEXT.',
    shut: 'Still changing? (shh)|Lock in your mouth first.',
    take: 'Three changes, three more months. (stamp)|Five months total. Booked.',
    gun: "(right after they switch, so does the clerk) Fine, I'm changing too:|you, to the back. NEXT.",
  },
  shutter: ["(pulls the shutter) That's it for today!|Your numbers are good tomorrow.", '(shutter all the way down, through the gap) Next— tomorrow.', 'CLOSED! (shutter slams) … (lifts it an inch)|See you in two months.'],
  boss: {
    name: 'The Ex-Boss',
    steps: [
      { says: 'Five-twenty cups. Tomorrow morning. Is that a problem?', sign: '520 cups', take: 'No problem. (stamp)|Tomorrow morning, two months from now.', gun: 'Tomorrow morning? (points at the door)|Wait outside till then.', shut: "Is that a problem? (cuts in)|Yes. You're still talking." },
      { says: 'Every cup a different sugar level. Cup one, thirty percent. Cup two, thirty-one. Cup three—', sign: 'Sugar chart\nper cup', shut: '(cuts in) Golden ratio.|All five-twenty. Same.', gun: 'Thirty, thirty-one? (points at the door)|Count your way outside.', take: '(stamp) Sugar chart received.|Final answer in two months: full sugar.' },
      { says: 'Put my company\'s tax ID on it. List it as "meeting supplies."', sign: 'Tax ID\nmeeting supplies', gun: "Meeting supplies? (points at the door)|The meeting room's outside.", shut: 'Read the tax ID once.|Eight digits, not eight meetings.', take: '(stamp, hands receipt) Tax ID, noted.|Item: two-fifty. Out of a thousand.' },
      { says: 'Five-twenty is steep. Discount it. Four hundred.', sign: '400 cups', take: 'Four hundred.|(stamp) Fine.' },
      { says: 'Three hundred.', sign: '300 cups', take: 'Three hundred.|(stamp) Fine.' },
      { says: 'Two-fifty-one.', sign: '251 cups', take: 'Two-fifty-one.|(stamp) Fine.' },
      { says: '…Two-fifty! (smug)', sign: '250 cups', take: '(freezes, looks up) Two-fifty.|(stamp) Deal. Out of a thousand.' },
      { says: '(quietly) …Do you remember me?', sign: 'Remember me?', full: "(stares at them, for a long time) …I remember.|You're number two-fifty. Pick up in two months. NEXT!", take: "I remember.|You're number two-fifty.", gun: "I remember. (points at the door)|That's why. Scram.", shut: '(shh) I remember.|Not chatting.' },
    ],
    haggleWrong: { shut: 'Discount?|DISCOUNT your MOM! The golden ratio has one price!', gun: "Haggling? (points)|The market's that way." },
    again: '(he haggles again)', hold: 'HOLD Booked!',
  },
};
