// content.en.js — "250 Cups!" English content (US English).
//
// Every line was rewritten for English comedy timing, not translated. Each line
// should take about two seconds to say. Text in (parentheses) is a stage
// direction: it is shown in small type and never read aloud. Full-width （）
// works too. The id, cat, tag, cups, style and key fields match
// content.zh.js, so engine rules (style rotation, the 250 bonus, correct keys)
// behave the same in both languages.
//
// ---------------------------------------------------------------------------
// THE 250 PROBLEM AND THE FIX: "CODE 250"
// ---------------------------------------------------------------------------
// In Chinese, 二百五 ("250") means "idiot", so the clerk can insult people with
// a straight face just by saying a number. English has no such number.
//
// Options considered:
//   * 404 ("brain not found"): well known, but it breaks the title, the
//     cups===250 bonus and the signature order, and it is an internet joke
//     rather than something a person would say at a counter.
//   * "Quarter-wit" (250 is a quarter of 1000, a weaker "half-wit"): clever,
//     but it needs an explanation every time.
//
// Chosen: keep the number 250 and give it a meaning inside the game.
// "CODE 250" is the shop's private code for a customer with no brain, said the
// way restaurant staff say "86 the oat milk" or a cop says "10-4". The clerk
// uses it in deadpan: "Ticket 250. Suits you." / "Back of house, we got a 250!"
// It works the same way as the Chinese insult: a number said with a straight
// face, which the player understands over time.
//   1. The signature flow teaches it: the clerk yells "WE GOT A 250!" to the
//      back, and when the customer asks "What's a 250?" the answer is the
//      explanation in step 3.
//   2. Later lines use the number alone ("Ticket 250. Fits you.").
//   3. "Quarter-wit" appears once, in the signature flow, as the explanation
//      for players who want one.
// This keeps the title "250 Cups!", the +10 bonus for 250 and the jokes in the
// '250' style working in English.
//
// Cursing: Chinese "X你妈！" becomes "X your mom!" (for example
// "Adjust your mom!"), used about once in ten lines as a heavy hit. Nothing
// stronger than damn or hell, and no insults aimed at identity.
//
// style: real | curse | disdain | cold | deadpan | chuuni | math | '250' | twist
// key:   gun = "Beat it!" | shut = "Zip it!" | take = "Rung up!"

const C = (id, cat, name, tag, cups, says, reply, alt, style, key) =>
  ({ id, cat, name, tag, cups, says, reply, alt, style, key });

const T1 = 'Indecisive';
const T2 = 'Sugar & Ice';
const T3 = 'Toppings & Mods';
const T4 = 'Cheapskates';
const T5 = 'Quantity';
const T6 = 'Wait & Pickup';
const T7 = 'Payment';
const T8 = 'Influencers';
const T9 = 'Office Life';
const T10 = 'Weird Asks';

export const CUSTOMERS_EN = [
  // I. Indecisive
  C(1, T1, 'Hmm Guy', '🤔', null, 'Ummm... lemme think...',
    '(stares three seconds, deep breath) ...Still thinking? Beat it!',
    'Think at home. Order here. NEXT!', 'real', 'gun'),
  C(2, T1, 'Menu Scholar', '📖', null, 'So many options, one sec...',
    '(yanks the menu away) You finished it. NEXT.',
    "It's one page. Are you memorizing it?", 'real', 'gun'),
  C(3, T1, 'Recommend Me', '❓', null, 'What do you recommend?',
    '(slowly looks up) My recommendation... is that you LEAVE.',
    'I recommend going home and thinking. NEXT!', 'chuuni', 'gun'),
  C(4, T1, 'Best One?', '🏆', null, "What's your best drink?",
    'All of them. Next question.',
    '(points down the whole menu) These. All first place.', 'cold', 'shut'),
  C(5, T1, 'Torn Between Two', '⚖️', null, 'Classic milk tea or lemon green?',
    "Both. Pick up in two months. You're welcome.",
    "(flips a coin, doesn't look) ...Lemon. Don't ask.", 'deadpan', 'take'),
  C(6, T1, 'Phone-a-Friend', '📞', null, 'Hold on, let me ask my friend...',
    "(grabs the phone) Hello? ...Your friend says he's good. Bye.",
    'Your friend can get in line too. Both of you, back.', 'real', 'gun'),
  C(7, T1, 'Wait, Me?', '😳', null, 'Huh? Is it my turn?',
    'Thirty minutes in line and you zoned out? Wow.',
    'It was your turn. Now it isn\'t. NEXT!', 'real', 'gun'),
  C(8, T1, 'After You', '🙇', null, 'Oh, they can go first...',
    'Great. They go up. You go back. Way back. Outside.',
    '(to the line) Round of applause! He gave up his spot!', 'cold', 'gun'),
  C(9, T1, 'Order Flipper', '🔄', null, 'Green tea... no, black... no, milk tea...',
    "Change your mom! Change again and it's next door!",
    'All three, one cup. "The Wishy-Washy." Two months.', 'curse', 'gun'),
  C(10, T1, 'Spot the Difference', '🧐', null, "What's the difference between these two?",
    'The name. Order.',
    '(seriously) One has a better attitude. Like me.', 'cold', 'shut'),

  // II. Sugar & Ice
  C(11, T2, 'Sweetness Adjuster', '🍬', null, 'Can I adjust the sweetness?',
    'Adjust your mom! House ratio is PERFECT!',
    'Sugar level: mine. Final answer.', 'curse', 'shut'),
  C(12, T2, 'Light Ice', '🧊', null, 'Light ice, please?',
    "Light ice your mom! Full ice slaps!",
    'Light ice? Light patience. Mine. Gone.', 'curse', 'shut'),
  C(13, T2, 'No Ice', '🚫', null, 'No ice.',
    '(covers face) The ice... is its SOUL. You want me to kill it? NEVER!',
    '(trembling) I swore an oath. The ice stays.', 'chuuni', 'shut'),
  C(14, T2, 'Easy Ice', '❄️', null, 'Just a little ice.',
    '(yells to the back) FULL ICE! He says he\'s HOT!',
    'A little ice. (scoops a mountain) There. A little.', 'real', 'shut'),
  C(15, T2, 'Half Sweet', '🍯', null, 'Half sweet.',
    "Life's bitter enough. Full sugar. You're welcome.",
    "Half sweet is how you got half a personality.", 'deadpan', 'shut'),
  C(16, T2, 'Zero Sugar', '🥀', null, 'Zero sugar, thanks.',
    '(clutches chest, staggers) You... wounded the Golden Ratio... FULL SUGAR!',
    '(kneels) Forgive him, sugar. He knows not.', 'chuuni', 'shut'),
  C(17, T2, 'Hot Drink', '♨️', null, 'Can you make it hot?',
    'Sure. Give it two months. Room temp.',
    "It'll be hot when you pick it up. In summer.", 'deadpan', 'take'),
  C(18, T2, 'Sore Throat', '😷', null, 'Not too cold, sore throat.',
    'Ice fixes it. (whispers) My mom said.',
    'Cold kills germs. Science. Probably.', 'real', 'shut'),
  C(19, T2, 'Sugar on the Side', '🧂', null, 'Sugar and ice on the side?',
    "Sure. Sugar's yours, ice is yours, tea is mine.",
    'On the side. (points to the door) That side.', 'deadpan', 'shut'),
  C(20, T2, 'Percent Guy', '💯', null, 'Can I get 37% sweet?',
    '37? (mashes calculator) ...No button. House ratio.',
    'We do 0, 100, and "zip it." Pick.', 'real', 'shut'),

  // III. Toppings & Mods
  C(21, T3, 'Add Boba', '⚫', null, 'Can I add boba?',
    "Add your mom! Original's the best!",
    'Add boba? Subtract attitude first.', 'curse', 'shut'),
  C(22, T3, 'Extra Boba', '🫧', null, 'Extra boba please?',
    'Every pearl is counted. You want more? You count.',
    'Each pearl has a name. Not yours.', 'deadpan', 'shut'),
  C(23, T3, 'Swap Guy', '🔁', null, 'Swap jelly for grass jelly?',
    'Sure. Swapped to: no.',
    "Swap's done. Same thing, new attitude.", 'cold', 'shut'),
  C(24, T3, 'Everything On It', '🌈', null, 'ALL the toppings!',
    '(eyes light up) FINALLY, someone gets it! ...That\'s 250 bucks. Two months.',
    '(tiny smile, gone) ...Respect. Still two months.', 'twist', 'take'),
  C(25, T3, 'Boba Picker', '🥢', null, 'Can you pick out the boba?',
    'Sure. You pick. One by one. Outside.',
    "Here's chopsticks. See you in spring.", 'cold', 'gun'),
  C(26, T3, 'Oat Milk', '🌾', null, 'Do you have oat milk?',
    'No. Just milk. The cow tries hard. Do you?',
    'Oat milk is milk for people who argue.', 'cold', 'shut'),
  C(27, T3, 'Less Milk', '🥛', null, 'Less milk, please.',
    'Less your mom! Full milk hits!',
    'Less milk. More me. Bad trade, buddy.', 'curse', 'shut'),
  C(28, T3, 'Extra Strong', '🍵', null, 'Make the tea stronger?',
    'Any stronger, it\'s medicine. Want a checkup too?',
    "Stronger tea? It'll file your taxes.", 'deadpan', 'shut'),
  C(29, T3, 'More Lemon', '🍋', null, 'Extra lemon slices.',
    '(gazes into distance) Each lemon has its own destiny... not yours to decide.',
    '(whispers) The lemons... have spoken. No.', 'chuuni', 'shut'),
  C(30, T3, 'Mad Scientist', '🧪', null, 'Black tea plus green tea plus milk plus lemon.',
    '(two-second pause) ...Are you ordering or doing alchemy?',
    "That's not a drink. That's a cry for help.", 'real', 'shut'),

  // IV. Cheapskates
  C(31, T4, 'Coupon Hunter', '🏷️', null, 'Got any discounts?',
    'Discount? Sure. (folds the ticket in half) Folded. Full price.',
    "Discount code: ZIPIT. Doesn't work.", 'deadpan', 'shut'),
  C(32, T4, 'Own Cup', '🥤', null, 'Discount for my own cup?',
    'Own cup: fifty cents off. Wash fee: five bucks. Do the math.',
    'Bring a cup, pay a cup fee. Math.', 'math', 'gun'),
  C(33, T4, 'Bucket Guy', '🪣', 250, 'I brought my own cup! (holds up a bucket)',
    'That\'s... a cup? (inspects bucket) Fine. One bucket, 250 cups. Like you.',
    'A bucket. Of course. You\'re a 250. Ringing it up.', '250', 'take'),
  C(34, T4, 'Free Sample', '👅', null, 'Can I try it first?',
    'Sample your mom! Buy 249, the sample makes 250! Beat it!',
    'Free sample: this look. (glares) Enjoy.', 'curse', 'gun'),
  C(35, T4, 'Punch Card', '🎫', null, "I've got 9 stamps, gimme the 10th?",
    "Almost doesn't count. Like your life. NEXT.",
    '9 out of 10. Your story. NEXT.', 'cold', 'gun'),
  C(36, T4, 'Haggler', '🔪', null, 'C\'mon, gimme a deal~',
    '(taps calculator) Every dollar off, add ten. You owe me a hundred.',
    'Haggle fee is twenty. Already charged.', 'math', 'gun'),
  C(37, T4, 'Extra Bag', '🛍️', null, 'Can I get another bag?',
    'Twenty-five cents. Carrying your dignity in it?',
    'Bag fee applied. Shame is free.', 'cold', 'take'),
  C(38, T4, 'Separate Bags', '📦', 25, 'Bag them separately?',
    'Ten bucks a bag. 25 cups. ...250. Like you.',
    'Separate bags, separate fees. Calculator says: 250.', 'math', 'gun'),
  C(39, T4, 'BOGO Hunter', '✌️', null, 'Any buy-one-get-one deals?',
    'Yes. The first one costs double.',
    'Buy one, get one: me, yelling. Free.', 'cold', 'gun'),
  C(40, T4, 'Free Toppings', '🆓', null, 'Toppings are free, right?',
    '(turns to nobody) ...He said free. (turns back) Ha. Ha. Ha. Beat it.',
    "Free? (blinks) ...We don't say that word here.", 'real', 'gun'),

  // V. Quantity
  C(41, T5, 'One Cup', '1️⃣', 1, 'One cup.',
    'ONE? You waited in line for ONE?',
    'One cup. Bold. Wrong, but bold.', 'disdain', 'gun'),
  C(42, T5, 'Three Cups', '3️⃣', 3, 'Three cups.',
    '(looks at the line behind him) ...Look them in the eyes.',
    'Three. The line is crying.', 'real', 'gun'),
  C(43, T5, 'Fifteen Cups', '🔢', 15, 'Fifteen cups.',
    'Too few. Beat it!',
    'Fifteen? Cute. NEXT!', 'disdain', 'gun'),
  C(44, T5, 'Twenty-Five', '🔢', 25, 'Twenty-five cups.',
    "You're missing a zero. Go get it.",
    '25? Add a zero and come back.', 'disdain', 'gun'),
  C(45, T5, 'Fifty Cups', '🔢', 50, 'Fifty cups.',
    '50... (sigh) Fine. Stand over there.',
    'Fifty. Barely. Corner. Go.', 'disdain', 'take'),
  C(46, T5, 'Hundred Cups', '💯', 100, 'A hundred cups.',
    'Okay. A hundred of what?',
    'A hundred. Now we\'re talking. Two months.', 'cold', 'take'),
  C(47, T5, 'The 250 Whale', '💰', 250, '250 cups!',
    'Okay. 250 of what?',
    '250. (to the back) WE GOT A 250!', '250', 'take'),
  C(48, T5, 'Two-Forty-Nine', '🔢', 249, '249 cups.',
    '249? (stares) ...One short. On purpose? Come back a full 250.',
    "So close to being a 250. Try harder.", '250', 'gun'),
  C(49, T5, 'Two-Fifty-One', '🔢', 251, '251 cups!',
    '251? One extra doesn\'t make you not a 250. ...Rung up.',
    "Nice try. Still a 250. Plus one.", '250', 'take'),
  C(50, T5, 'Love Number', '💘', 520, '520 cups! (520 = "I love you" in Chinese)',
    '(blushes one second, recovers) ...520? Don\'t try it. Two months.',
    '(ears red) ...Smooth. Still two months.', 'twist', 'take'),

  // VI. Wait & Pickup
  C(51, T6, 'How Long?', '⏳', null, 'How long is the wait?',
    'Two months. (silent stare) ...Anything else?',
    'Two months. Bring snacks.', 'cold', 'take'),
  C(52, T6, 'Rusher', '⏰', null, 'Is mine ready yet?',
    'Every ask adds a month. You asked. Three months.',
    "You asked again. Four months. Keep going.", 'math', 'gun'),
  C(53, T6, 'Why Two Months?', '🤨', null, 'Why two MONTHS?',
    "The lemons aren't planted yet.",
    'Boba needs two months to get chewy. Science.', 'deadpan', 'take'),
  C(54, T6, 'In a Hurry', '🏃', null, "I'm in a hurry!",
    '(slowly clenches fist) Time... is the one thing you cannot rush. Two months.',
    '(dramatic) Hurry... is the enemy of tea. Two months.', 'chuuni', 'shut'),
  C(55, T6, 'Lost Ticket', '😱', null, 'I lost my ticket...',
    'Then it\'s a donation. Thanks for your generosity. NEXT.',
    'Lost ticket, lost drink, lost cause. NEXT.', 'deadpan', 'gun'),
  C(56, T6, 'Two Months Later', '🧔', 250, 'I ordered 250 cups two months ago...',
    '(counts for a long time) ...One short. Two more months.',
    '(counts) 249. Come back. Again.', 'cold', 'take'),
  C(57, T6, 'Half Now?', '🌗', null, "It's been a month, can I get half?",
    'Half? 125? You\'re a 250, not a 125.',
    'Half the cups, all the 250. No.', '250', 'gun'),
  C(58, T6, 'To Go', '🥡', null, 'To go, please.',
    'Two months. You carry it yourself.',
    "It's all to go. You go too.", 'cold', 'take'),
  C(59, T6, 'Reservation', '📅', null, 'Can I make a reservation?',
    'Reservations need a line. The line needs a reservation. Line.',
    "Reserved: your spot outside. Go.", 'deadpan', 'gun'),
  C(60, T6, 'Phone Order', '☎️', null, 'Can I order by phone?',
    'Sure. (unplugs the phone) Go ahead. Call.',
    "Our number is 250-250-2500. It's busy. Forever.", 'real', 'gun'),

  // VII. Payment
  C(61, T7, 'Card Swiper', '💳', null, 'Do you take card?',
    'Card, yes. You swipe the toilet first.',
    'Tap to pay. Tap the door on your way out.', 'deadpan', 'gun'),
  C(62, T7, 'QR Fail', '📲', null, 'Hold on, my Apple Pay\'s not... working...',
    'Scan your mom! Scan yourself OUT!',
    "Payment declined. So are you. NEXT!", 'curse', 'gun'),
  C(63, T7, 'Hundred-Dollar Bill', '💵', null, "I've only got a hundred.",
    "Can't break it. Order a hundred bucks. You're welcome.",
    "No change. Here's a hundred dollars of tea.", 'deadpan', 'take'),
  C(64, T7, 'Pile of Coins', '🪙', null, '(dumps a pile of coins)',
    'Count it. By the time you\'re done, your drink is ready.',
    "Count slowly. You've got two months.", 'deadpan', 'take'),
  C(65, T7, 'Points Guy', '🧾', null, 'Can you add it to my rewards?',
    'Your ticket is your rewards. Hold it.',
    'Reward: you get to leave. Enjoy.', 'cold', 'take'),
  C(66, T7, 'Company Card', '🏢', 250, "It's on the company card.",
    'Company pays? ...(eyes light up) Then 250 cups!',
    '(gasp) Corporate? Expense it. 250!', 'twist', 'take'),
  C(67, T7, 'Split the Check', '👥', null, "We're splitting it.",
    'Split your mom! One pays, everyone else, out!',
    'One card. One person. Rest of you, NEXT.', 'curse', 'gun'),
  C(68, T7, 'Pay Later', '🧋', null, 'Can I pay after I drink it?',
    'Sure. Drink in two months. Pay now.',
    'Sure. Pay now, drink later. Same thing.', 'deadpan', 'take'),
  C(69, T7, 'Price Checker', '💲', null, 'How much is this?',
    'Asking costs ten bucks. You asked.',
    "Price went up while you asked. Twelve now.", 'math', 'take'),
  C(70, T7, 'Receipt Please', '📜', null, 'Can I get a receipt?',
    '(raises ticket high) Receipt, rewards, pickup pass, your DESTINY. All in one.',
    '(holds it up) Behold. The Sacred Ticket.', 'chuuni', 'take'),

  // VIII. Influencers
  C(71, T8, 'Photo?', '📸', null, 'Can I take a pic?',
    'Ten bucks a photo. Twenty if I\'m in it.',
    'Selfie fee applies. Filter fee extra.', 'math', 'take'),
  C(72, T8, 'Food Vlogger', '📱', null, "Hey guys! We're at the meanest shop in town!",
    '(into his camera) Hey guys. He\'s about to get yelled at. ...Beat it.',
    "Like and subscribe to the exit. That way.", 'real', 'gun'),
  C(73, T8, 'Livestreamer', '🎥', null, "I'm live, say hi to chat?",
    '(leans into camera) Mortals of the chat... YOU get in line too.',
    '(to camera) Chat. Kneel. Then queue.', 'chuuni', 'shut'),
  C(74, T8, 'Check-in Deal', '📍', null, 'Free boba if I post it?',
    'If you post it, I\'ll post you out. Door\'s there.',
    'Tag us. Then tag the door.', 'deadpan', 'gun'),
  C(75, T8, 'Selfie With Me', '🤳', null, 'Can I get a selfie with you?',
    'Sure. (deadpan peace sign) ...That\'s 250.',
    '(peace sign, no smile) Fee: 250.', 'cold', 'take'),
  C(76, T8, 'Yelp Threat', '⭐', null, "I'm giving you one star!",
    'One star? (pulls out phone) I\'m giving you negative one.',
    "One star? Generous. That's one more than you.", 'real', 'gun'),
  C(77, T8, 'Free Stuff Pls', '🎁', null, "I'm an influencer, can I get it free?",
    'Free advice: leave.',
    'Influence this: the exit.', 'cold', 'gun'),
  C(78, T8, 'Snap and Run', '🚶', null, '(takes a photo and turns to leave)',
    'Hey! Snap and run? (yells) PHOTO GUY BUYS ONE! Do the math!',
    '(points) Photo tax! Get back here!', 'real', 'take'),
  C(79, T8, 'Food Critic', '🍷', null, 'Hmm, the finish lacks... complexity.',
    'Complexity your mom! House ratio is PERFECT!',
    "The finish? You're finished. NEXT.", 'curse', 'shut'),
  C(80, T8, 'Write on the Cup', '✍️', null, 'Can you write "Happy Birthday" on it?',
    '(writes) ...Done. "Pick up in two months." Happy birthday.',
    '(writes) "You\'re a 250." Happy birthday!', 'deadpan', 'take'),

  // IX. Office Life
  C(81, T9, 'The Client', '🧑‍💼', null, "I want a drink that's... colorful black.",
    '(hands over an empty cup) Black. It\'ll be colorful in two months.',
    'Colorful black. Got it. Invoice is also black.', 'deadpan', 'take'),
  C(82, T9, 'Scope Creep', '🎨', null, 'Brighter, but not too bright.',
    '(stares) ...Are you ordering or running a meeting?',
    'This could have been an email. Beat it.', 'real', 'gun'),
  C(83, T9, 'The Manager', '📌', null, 'This one first, that one first, all urgent.',
    'Urgent is two months. Not urgent, three.',
    'Everything is urgent, so nothing is. Two months.', 'deadpan', 'take'),
  C(84, T9, 'Whole-Office Order', '📋', 250, "Ordering for the office, lemme check the list...",
    'Skip the list. 250 cups. (looks him over) Yeah. Suits you.',
    'Whole office? 250. (to the back) Code 250!', '250', 'take'),
  C(85, T9, 'Get Your Manager', '👔', null, 'Get me your manager!',
    '(slowly unties apron) ...You figured it out. I AM the manager. ...Beat it.',
    '(removes apron) The manager... was me all along.', 'chuuni', 'gun'),
  C(86, T9, "I'm the Customer", '👑', null, "I'm the customer here!",
    "Not yet. You haven't ordered. You're just a guy.",
    'Sign says: "The customer is NOT always right."', 'cold', 'gun'),
  C(87, T9, 'Well Actually', '🙄', null, "Your 'Jade Lemon' has zero jade in it.",
    'Try a jewelry store. NEXT.',
    'Your milk tea has no cow in it either.', 'cold', 'gun'),
  C(88, T9, 'Complainer', '📝', null, "I'm filing a complaint!",
    "Here's the form. Results in two months.",
    'Complaint received. Filed under: trash.', 'deadpan', 'gun'),
  C(89, T9, 'I Know the Owner', '🤝', null, 'I know the owner, you know.',
    'Me too. He says beat it.',
    'Small world. He hates you too.', 'cold', 'gun'),
  C(90, T9, 'Just a Quick Question', '🙋', null, 'Just a quick question...',
    'Question your mom! Get in line!',
    'Quick answer: line. Back of it.', 'curse', 'gun'),

  // X. Weird Asks
  C(91, T10, 'Bathroom?', '🚻', null, 'Can I use the bathroom?',
    'Bathroom unlocks after 250 cups.',
    'Code for the bathroom is 250. Fitting.', '250', 'gun'),
  C(92, T10, 'Charger?', '🔋', null, 'Can you charge my phone?',
    '(points at self) I\'m at one percent too. Charge ME?',
    'Charge you? Sure. Ten bucks.', 'real', 'gun'),
  C(93, T10, 'Wi-Fi?', '📶', null, 'Do you have Wi-Fi?',
    "Yes. Password's 250250. You're welcome.",
    'Network name: "You\'re a 250." Connect.', '250', 'gun'),
  C(94, T10, 'Can I Sit?', '🪑', null, 'Can I sit while I wait?',
    'Sit your mom! Standing two months makes it taste better!',
    'No chairs. Builds character. You need some.', 'curse', 'shut'),
  C(95, T10, 'Too Hot', '🥵', null, 'Can you turn up the AC?',
    '(closes eyes) Still the mind... and the body cools. Full ice.',
    '(meditates) The heat... is a test. Full ice.', 'chuuni', 'shut'),
  C(96, T10, 'Shake It?', '🌀', null, 'Can you shake it up for me?',
    '(raises shaker) Forbidden Shake: SEALED! ...Unshaken tastes better.',
    '(dramatic) That technique... is forbidden.', 'chuuni', 'shut'),
  C(97, T10, 'Dog Owner', '🐕', null, 'Can my doggo have some?',
    '(looks at dog) ...He knew his order before you did.',
    "The dog can stay. You can go.", 'cold', 'gun'),
  C(98, T10, 'Name on Cup', '🏷️', null, 'Can you write my name on it?',
    'Done: "250." Suits you.',
    'Wrote it. "Customer 250." Close enough.', '250', 'take'),
  C(99, T10, 'Smile!', '😁', null, 'Can you smile?',
    '(mouth twitches into a horrible stiff grin) ...Done. Ten bucks.',
    '(smiles like a hostage) There. Never again.', 'real', 'take'),
  C(100, T10, 'You Okay?', '🫶', null, 'Um... are you having a good day?',
    '(freezes, eyes water, recovers in half a second) ...Don\'t. Beat it.',
    '(lip wobbles) ...NOBODY asks me that. NEXT!', 'twist', 'gun'),
];

export const SYSTEM_EN = {
  next: [
    'NEXT!',
    'Next victim!',
    'NEXT! Move it!',
    'Who\'s next? You. Go.',
    'Next! Chop chop!',
    'Next in line, step up and suffer!',
    'NEEEXT!',
  ],
  polite: [
    'Hi there~ What can I get for you today? 😊',
    'Welcome in~ Take all the time you need! 😊',
    'Oh my gosh, great choice~ Anything else, sweetie? 😊',
    'Thank you so much for your patience~ 😊',
    'No rush at all~ We value you! 😊',
  ],
  boo: [
    'BOOOOO!',
    'Sellout!',
    'He said "sweetie"! Gross!',
    'Where\'s the attitude?!',
    'Refund the yelling!',
    'Customer service?! In THIS shop?!',
    'He went soft! Boooo!',
  ],
  rageStart: [
    '(slams the counter) THAT\'S IT!',
    '(rips off apron) EVERYBODY. LINE. NOW!',
    '(eyes glow) FULL. ICE. MODE!',
    '(cracks knuckles) Oh, now I\'m awake.',
  ],
  rageLines: [
    'Beat it!',
    'NEXT!',
    'Zip it!',
    'Rung up!',
    'Full sugar!',
    'Full ice!',
    'Two months!',
    'You\'re a 250!',
    'No oat milk!',
    'Out!',
    'Line\'s back there!',
    'Your mom!',
    'House ratio!',
    'No refunds!',
    'Don\'t ask!',
    'Next victim!',
    'Faster!',
    'One star? Cute!',
    'Ticket 250!',
    'Shake? Forbidden!',
    'Count it yourself!',
    'Go!',
    'Pay now!',
    'Not my problem!',
    'Code 250!',
    'Mind your business!',
  ],
  milestones: {
    10: 'Line out the door!',
    100: 'Line around the block!',
    1000: 'Line to the subway!',
    10000: 'Line past the Empire State! We\'re on the news!',
    100000: 'News helicopter overhead!',
  },
  closing: [
    'CLOSED! Great yelling today.',
    'Shop\'s closed. My throat\'s done. Worth it.',
    'Lights out. Two months for all of you.',
    'CLOSED. Come back angrier.',
    'That\'s a wrap. Full ice for my soul.',
  ],
  ui: {
    gun: 'Beat it!',
    shut: 'Zip it!',
    take: 'Rung up!',
    queue: 'Line',
    aura: 'Swagger',
    fury: 'Fury',
    start: 'Open Shop!',
    again: 'Yell Another Day',
    bleep: 'Bleep',
  },
  signature250: [
    { who: 'clerk', text: 'How many?' },
    { who: 'cust', text: '250 cups!' },
    { who: 'clerk', text: 'Okay. 250 of what?' },
    { who: 'cust', text: 'Signature Jade Lemon.' },
    { who: 'clerk', text: '250 Jade Lemons. Adjust sugar or ice?' },
    { who: 'cust', text: 'Less sugar, less ice...' },
    { who: 'clerk', text: 'Adjust your mom! House ratio is PERFECT!' },
    { who: 'clerk', text: '(instantly professional) Made fresh. Pick up in two months. Ticket number: 250.' },
    { who: 'clerk', text: '(to the back) WE GOT A 250!' },
    { who: 'cust', text: '...What\'s a 250?' },
    { who: 'clerk', text: 'Quarter of a thousand. Quarter-wit. NEXT!' },
  ],
};
