#!/usr/bin/env python3
"""Regenerate the self-hosted font subsets in game/fonts/ from the current text (docs/art-direction-v2.md 3.2).

Every character the game can show comes from src/*.js, index.html and style.css (Chinese is Traditional at the
source), so the fonts are cut down to exactly those characters plus printable ASCII and the usual CJK punctuation.
All fonts are SIL OFL 1.1; their license texts are copied next to the subsets.

    pip install fonttools brotli
    python3 tools/fonts/subset.py            # run from game/; downloads the source fonts once into tools/fonts/.cache/
    python3 tools/fonts/subset.py --src=DIR  # use source files already on disk (same file names as SOURCES below)

Writes game/fonts/*.woff2, game/fonts/OFL-*.txt and game/fonts/subset.json (per font: the characters it covers
and the requested characters its source font does not have). tools/check-content.mjs F1 reads subset.json and fails
when a character used in the source is in neither list, i.e. when this script needs to be run again.
"""
import io
import json
import re
import sys
import tarfile
import urllib.request
from pathlib import Path

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

GAME = Path(__file__).resolve().parents[2]
OUT = GAME / 'fonts'
CACHE = Path(__file__).resolve().parent / '.cache'
GF = 'https://raw.githubusercontent.com/google/fonts/main/ofl'

# source file -> download URL (Google Fonts repository, OFL) / the DSEG npm tarball (OFL)
SOURCES = {
    'Huninn-Regular.ttf': f'{GF}/huninn/Huninn-Regular.ttf',
    'NotoSansTC[wght].ttf': f'{GF}/notosanstc/NotoSansTC%5Bwght%5D.ttf',
    'LXGWWenKaiTC-Bold.ttf': f'{GF}/lxgwwenkaitc/LXGWWenKaiTC-Bold.ttf',
    'Baloo2[wght].ttf': f'{GF}/baloo2/Baloo2%5Bwght%5D.ttf',
    'DSEG7Classic-Bold.ttf': 'npm:dseg@0.46.0:package/fonts/DSEG7-Classic/DSEG7Classic-Bold.ttf',
}
LICENSES = {
    'OFL-huninn.txt': f'{GF}/huninn/OFL.txt',
    'OFL-noto-sans-tc.txt': f'{GF}/notosanstc/OFL.txt',
    'OFL-lxgw-wenkai-tc.txt': f'{GF}/lxgwwenkaitc/OFL.txt',
    'OFL-baloo2.txt': f'{GF}/baloo2/OFL.txt',
    'OFL-dseg.txt': 'npm:dseg@0.46.0:package/DSEG-LICENSE.txt',
}

# output -> (source, wght instance or None, character set name)
JOBS = {
    'huninn.woff2': ('Huninn-Regular.ttf', None, 'all'),
    'noto-sans-tc-500.woff2': ('NotoSansTC[wght].ttf', 500, 'all'),
    'noto-sans-tc-700.woff2': ('NotoSansTC[wght].ttf', 700, 'all'),
    'noto-sans-tc-900.woff2': ('NotoSansTC[wght].ttf', 900, 'all'),
    'wenkai-tc-700.woff2': ('LXGWWenKaiTC-Bold.ttf', None, 'all'),
    'baloo2-800.woff2': ('Baloo2[wght].ttf', 800, 'latin'),
    'dseg7-bold.woff2': ('DSEG7Classic-Bold.ttf', None, 'ascii'),
}

EXTRA = '…—～「」『』、。，．・·：；！？（）《》〈〉【】％＋－×÷★☆▸▶◀←→↑↓0123456789'


def used_chars():
    """Every non-control character in src/*.js, index.html and style.css, plus ASCII and EXTRA (sorted string)."""
    files = sorted((GAME / 'src').glob('*.js')) + [GAME / 'index.html', GAME / 'style.css']
    chars = set(chr(c) for c in range(0x20, 0x7F)) | set(EXTRA)
    for f in files:
        for ch in f.read_text(encoding='utf-8'):
            if ord(ch) >= 0xA0 and not re.match('[\u200b-\u200f\u2028-\u202f\ufe00-\ufe0f\ufeff]', ch):
                chars.add(ch)
    return ''.join(sorted(chars))


def fetch(url):
    if url.startswith('npm:'):
        _, spec, member = url.split(':', 2)
        name, ver = spec.split('@')
        tgz = CACHE / f'{name}-{ver}.tgz'
        if not tgz.exists():
            tgz.write_bytes(urllib.request.urlopen(f'https://registry.npmjs.org/{name}/-/{name}-{ver}.tgz').read())
        with tarfile.open(tgz) as t:
            return t.extractfile(member).read()
    return urllib.request.urlopen(url).read()


def source(name, src_dir):
    p = (src_dir or CACHE) / name
    if not p.exists():
        if src_dir:
            sys.exit(f'missing source font {p}')
        CACHE.mkdir(parents=True, exist_ok=True)
        print(f'download {name}')
        p.write_bytes(fetch(SOURCES[name]))
    return p


def main():
    src_dir = next((Path(a[6:]) for a in sys.argv[1:] if a.startswith('--src=')), None)
    OUT.mkdir(exist_ok=True)
    allc = used_chars()
    sets = {
        'all': allc,
        'latin': ''.join(c for c in allc if ord(c) < 0x2E80),
        'ascii': ''.join(chr(c) for c in range(0x20, 0x7F)),
    }
    manifest = {'note': 'generated by tools/fonts/subset.py; checked by tools/check-content.mjs F1', 'fonts': {}}
    for out, (src, wght, set_name) in JOBS.items():
        want = sets[set_name]
        font = TTFont(source(src, src_dir))
        cmap = font.getBestCmap()
        have = ''.join(c for c in want if ord(c) in cmap)
        missing = ''.join(c for c in want if ord(c) not in cmap and ord(c) > 0x20)
        opts = subset.Options()
        opts.flavor = 'woff2'
        opts.layout_features = ['kern', 'liga', 'calt', 'ccmp', 'locl', 'mark', 'mkmk', 'palt', 'vert', 'tnum']
        opts.name_IDs = ['*']
        opts.name_languages = ['*']
        opts.notdef_outline = True
        opts.hinting = False
        opts.desubroutinize = True
        sub = subset.Subsetter(opts)
        sub.populate(unicodes=[ord(c) for c in have])
        sub.subset(font)
        if wght is not None and 'fvar' in font:
            font = instancer.instantiateVariableFont(font, {'wght': wght}, updateFontNames=False)
        font.flavor = 'woff2'
        buf = io.BytesIO()
        font.save(buf)
        (OUT / out).write_bytes(buf.getvalue())
        manifest['fonts'][out] = {'set': set_name, 'chars': have, 'unavailable': missing}
        print(f'{out}: {len(have)} chars, {len(buf.getvalue()) // 1024} KB' + (f', {len(missing)} not in source' if missing else ''))
    for name, url in LICENSES.items():
        dest = OUT / name
        if not dest.exists():
            dest.write_bytes(fetch(url))
    (OUT / 'subset.json').write_text(json.dumps(manifest, ensure_ascii=False, indent=1) + '\n', encoding='utf-8')


if __name__ == '__main__':
    main()
